### ISSUE TITLE
Minecraft server wont start with newest kubejs and Rhino version

### ISSUE THREAD

**Issue by Leno2206** [KubeJS-Mods/KubeJS#154]
Suspected Mods: Forge (forge), Forge (forge)[14:32:21] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
KubeJS (kubejs) has failed to load correctly
§7java.lang.NoClassDefFoundError: dev/latvian/mods/rhino/EvaluatorException
]
at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211] {}
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211] {}
at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge.jar:36.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge.jar:?] {re:classloading}
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge.jar:?] {re:classloading}
at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge.jar:?] {re:classloading}

**Comment by MaxNeedsSnacks** [comment]
Please don’t just use „latest“ to describe what mod versions you are using, what concrete versions are you **actually** currently using

**Comment by Leno2206** [comment]
rhino-1605.1.1-build.23.jar
kubejs-forge-1605.3.11-build.31.jar

**Comment by Leno2206** [comment]
The issue kind of fixed itself when i changed the ftb chunks version? idk

**Comment by Leno2206** [comment]
ill just close it caus 1.16 is giving me mental break down and im going back to 1.12.2
