### ISSUE TITLE
Server Crash with all the KubeJS mods.

### ISSUE THREAD

**Issue by Jerome226** [KubeJS-Mods/KubeJS#170]
I'm using latest versions of all KubeJS mods.
The crash only happens on server and with the KubeJS Addon (i think the create one) because the bug doesnt happens with KubeJS alone.
I have a lot of other mods. (https://github.com/PufferTeam/SuperPack/blob/main/MODLIST.txt)

![image](https://user-images.githubusercontent.com/55724525/127753556-0377122c-0345-4d2b-a7bc-21c6095736ab.png)

```
[31juil.2021 18:10:08.067] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[31juil.2021 18:10:08.067] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[31juil.2021 18:10:08.068] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[31juil.2021 18:10:08.068] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[31juil.2021 18:10:08.069] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[31juil.2021 18:10:08.071] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[31juil.2021 18:10:08.071] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[31juil.2021 18:10:08.072] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[31juil.2021 18:10:08.072] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[31juil.2021 18:10:08.073] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[31juil.2021 18:10:08.073] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[31juil.2021 18:10:08.074] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[31juil.2021 18:10:08.074] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[31juil.2021 18:10:08.075] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[31juil.2021 18:10:08.076] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[31juil.2021 18:10:08.077] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[31juil.2021 18:10:08.078] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 7 more
[31juil.2021 18:10:08.079] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.NoSuchMethodError: com.simibubi.create.AllRecipeTypes.getSerializer()Lnet/minecraft/item/crafting/IRecipeSerializer;
[31juil.2021 18:10:08.079] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at dev.latvian.kubejs.create.KubeJSCreatePlugin.addRecipes(KubeJSCreatePlugin.java:25)
[31juil.2021 18:10:08.080] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at dev.latvian.kubejs.server.ServerScriptManager.lambda$resourcePackList$3(ServerScriptManager.java:122)
[31juil.2021 18:10:08.080] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.util.ArrayList.forEach(ArrayList.java:1259)
[31juil.2021 18:10:08.081] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at dev.latvian.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:108)
[31juil.2021 18:10:08.081] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at dev.latvian.kubejs.server.ServerScriptManager.resourcePackList(ServerScriptManager.java:122)
[31juil.2021 18:10:08.082] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.resources.DataPackRegistries.modify$zgc000$resourcePackList(DataPackRegistries.java:529)
[31juil.2021 18:10:08.083] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.resources.DataPackRegistries.func_240961_a_(DataPackRegistries.java:72)
[31juil.2021 18:10:08.083] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.server.Main.main(Main.java:126)
[31juil.2021 18:10:08.084] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 13 more
```

Here is full logs from the server.
[latest.log](https://github.com/KubeJS-Mods/KubeJS/files/6911899/latest.log)

**Comment by LatvianModder** [comment]
Oh I see, its Create you havent updated, not my mods

**Comment by Jerome226** [comment]
Wait create had a update? My mistake.
