### ISSUE TITLE
(fabric) crash with iris and konkrete

### ISSUE THREAD

**Issue by Chuunkyz** [KubeJS-Mods/KubeJS#225]
if i install the latest kubejs, iris shaders and konkerete, the lib for fancymenu and drippy loading, i get an error when starting the instance, nothing in the crash logs, the game doesnt even start

**Comment by MaxNeedsSnacks** [comment]
Can you send me your latest.log please? Also what Minecraft and KubeJS version are you using?

**Comment by Chuunkyz** [comment]
Minecraft : 1.18 fabric 0.12.8
Kubejs : latest 1.18 build on cf (kubejs-fabric-1800.4.0-build.197.jar)

also here's my modpack
https://www.curseforge.com/minecraft/modpacks/benchmark-ii

you can try to add konkrete here, but it will break, aside if you remove kubejs

**Comment by Chuunkyz** [comment]
to be more precise, i have TWO crash logs when i try to start the game, the second has that :
java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.config.IrisConfig.areShadersEnabled()" because "net.coderbot.iris.Iris.irisConfig" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18+build.1)
	at net.coderbot.iris.Iris.loadShaderpack(Iris.java:152)
	at net.coderbot.iris.Iris.onRenderSystemInit(Iris.java:107)
	at com.mojang.blaze3d.systems.RenderSystem.handler$ckj000$iris$onRendererInit(RenderSystem:1908)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem:809)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:498)
	at net.minecraft.client.main.Main.main(Main:197)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
and the first has that :
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expandedstorage'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
...
**the problem isn't due to expanded storage, removing the mod will just result to an other mod in the new crash report** (i tried to remove a good amount of mods but this isn't a solution)
also, this is still a thing with the new kubejs, and konkrete, iris, sodium, and indium are all updated

**Comment by red2blue** [comment]
@Chuunkyz check latest.log 

When I get that crash in a crash log, it almost **always** has a different, real crash reason in latest.log 

NEC sometimes does that for some reason and idk why.
