### ISSUE TITLE
[1.18.1 Server] High RAM usage and "Potentially Dangerous" Errors

### ISSUE THREAD

**Issue by lulabyte** [KubeJS-Mods/KubeJS#284]
When I install this mod on my server (kubejs-forge-1801.4.2-build.298.jar, rhino-forge-1801.1.8-build.99.jar, architectury-3.6.17.jar), my CPU and RAM useage shoots up dramatically and I notice these two lines in the error log:

[05:12:37] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.

[05:12:37] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `flowing_milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.

Here's the full log:
(Thank you for your time!)
----------------------

[05:12:24] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.76, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, nogui]
[05:12:24] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Eclipse Adoptium
[05:12:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/sid_637640/minecraft_forge_118/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[05:12:25] [main/INFO]: Found mod file angelring-1.18-1.5.0.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file architectury-3.6.17.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file balm-2.4.1+0.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file carryon-1.18.1-1.17.0.7.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file cleancut-mc1.18-3.0-forge.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file clienttweaks-forge-1.18-7.0.0.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file configured-1.5.1-1.18.1.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file Controlling-forge-1.18.1-9.0+14.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file CosmeticArmorReworked-1.18.1-v1a.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file creeperconfetti-3.10.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file curios-forge-1.18.1-5.0.6.0.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file EditSign-1.18.1-2.2.7.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file elevatorid-1.18-1.8.3.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file FallingTree-1.18.1-3.2.0b2.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file inventorysorter-1.18-19.0.0.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file ironchest-1.18-13.0.7.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file jei-1.18.1-9.2.1.69.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file journeymap-1.18.1-5.8.0beta11.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file kubejs-forge-1801.4.2-build.298.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file MouseTweaks-forge-mc1.18-2.21.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file quickhomes-1.18.1-1.3.0-forge.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file rhino-forge-1801.1.8-build.99.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file signpost-1.18.1-2.00.4.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file sit-1.18-1.3.1.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file TravelersBackpack-1.18.1-7.0.1.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file waystones-forge-1.18.1-9.0.3.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file worldedit-mod-7.2.9.jar of type MOD with locator {mods folder locator at /home/sid_637640/minecraft_forge_118/mods}
[05:12:25] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.76.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bd2b28e
[05:12:25] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.76.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bd2b28e
[05:12:25] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.76.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bd2b28e
[05:12:25] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bd2b28e
[05:12:25] [main/INFO]: Found mod file forge-1.18.1-39.0.76-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bd2b28e
[05:12:26] [main/INFO]: Compatibility level set to JAVA_17
[05:12:26] [main/INFO]: Launching target 'forgeserver' with arguments [nogui]
[05:12:26] [main/WARN]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[05:12:35] [modloading-worker-0/INFO]: Looking for KubeJS plugins...
[05:12:35] [modloading-worker-0/INFO]: Found kubejs plugin
[05:12:35] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.76, for MC 1.18.1 with MCP 20211210.034407
[05:12:35] [modloading-worker-0/INFO]: MinecraftForge v39.0.76 Initialized
[05:12:35] [modloading-worker-0/INFO]: Done in 0 s
[05:12:35] [modloading-worker-0/INFO]: Loaded common.properties
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/desert/zombie/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/desert/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/plains/zombie/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/plains/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/savanna/zombie/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/savanna/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/snowy/zombie/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/snowy/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/taiga/zombie/houses]' to registry
[05:12:35] [modloading-worker-0/ERROR]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/taiga/houses]' to registry
[05:12:36] [modloading-worker-0/INFO]: Registered the class com.tiviacz.travelersbackpack.fluids.effects.WaterEffect as a FluidEffect for Water with the ID 0
[05:12:36] [modloading-worker-0/INFO]: Registered the class com.tiviacz.travelersbackpack.fluids.effects.LavaEffect as a FluidEffect for Lava with the ID 1
[05:12:37] [modloading-worker-0/INFO]: Hello, World! (You will only see this line once in console, during startup)
[05:12:37] [modloading-worker-0/INFO]: Loaded script startup_scripts:script.js in 0.176 s
[05:12:37] [modloading-worker-0/INFO]: Loaded 1/1 KubeJS startup scripts in 0.544 s
[05:12:37] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[05:12:37] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `flowing_milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[05:12:37] [modloading-worker-0/INFO]: Angel Ring's setup initialized.
[05:12:37] [Forge Version Check/INFO]: [enchdesc] Starting version check at https://updates.blamejared.com/get?n=enchdesc&gv=1.18.1
[05:12:38] [modloading-worker-0/INFO]: Got request to register class com.sk89q.worldedit.forge.ForgePlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@e41129f]
[05:12:38] [modloading-worker-0/INFO]: WorldEdit for Forge (version 7.2.9+e20e013) is loaded
[05:12:38] [main/INFO]: Initializing Packet Registries
[05:12:38] [Forge Version Check/INFO]: [enchdesc] Found status: BETA_OUTDATED Current: 9.0.11 Target: 9.0.13
[05:12:38] [Forge Version Check/INFO]: [editsign] Starting version check at https://raw.githubusercontent.com/RakSrinaNa/EditSign/1.18.1/update.json
[05:12:38] [Forge Version Check/INFO]: [editsign] Found status: UP_TO_DATE Current: 2.2.7 Target: null
[05:12:38] [Forge Version Check/INFO]: [controlling] Starting version check at https://updates.blamejared.com/get?n=controlling&gv=1.18.1
[05:12:38] [Forge Version Check/INFO]: [controlling] Found status: BETA Current: 9.0+14 Target: 9.0+14
[05:12:38] [Forge Version Check/INFO]: [travelersbackpack] Starting version check at https://gist.githubusercontent.com/Tiviacz1337/906937677aa472285dff9d6c2a189d5e/raw
[05:12:39] [Forge Version Check/INFO]: [travelersbackpack] Found status: UP_TO_DATE Current: 7.0.1 Target: null
[05:12:39] [Forge Version Check/INFO]: [configured] Starting version check at https://mrcrayfish.com/modupdatejson?id=configured
[05:12:39] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:12:39] [main/INFO]: Injecting existing registry data into this CLIENT instance
[05:12:39] [main/INFO]: Registry minecraft:block: Found a missing id from the world sophisticatedbackpacks:backpack
[05:12:39] [main/INFO]: Registry minecraft:block: Found a missing id from the world sophisticatedbackpacks:diamond_backpack
[05:12:39] [main/INFO]: Registry minecraft:block: Found a missing id from the world sophisticatedbackpacks:gold_backpack
[05:12:39] [main/INFO]: Registry minecraft:block: Found a missing id from the world sophisticatedbackpacks:iron_backpack
[05:12:39] [main/INFO]: Registry minecraft:block: Found a missing id from the world sophisticatedbackpacks:netherite_backpack
[05:12:39] [Forge Version Check/INFO]: [configured] Found status: BETA_OUTDATED Current: 1.5.1 Target: 1.5.3
[05:12:39] [Forge Version Check/INFO]: [angelring] Starting version check at https://www.curseforge.com/minecraft/mc-mods/angel-ring
[05:12:39] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18.1-39.0.76.jar%2368!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18.1-39.0.76.jar%2368!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!/:?]
	... 6 more
[05:12:39] [Forge Version Check/INFO]: [creeperconfetti] Starting version check at https://raw.githubusercontent.com/SR2610/Creeper-Confetti-Forge-Edition/main/creeperconfettiupdate.json
[05:12:39] [Forge Version Check/INFO]: [creeperconfetti] Found status: BETA Current: 3.10 Target: null
[05:12:39] [Forge Version Check/INFO]: [fallingtree] Starting version check at https://raw.githubusercontent.com/wiki/RakSrinaNa/FallingTree/assets/update.json
[05:12:39] [Forge Version Check/INFO]: [fallingtree] Found status: AHEAD Current: 3.2.0b2 Target: null
[05:12:39] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[05:12:39] [Forge Version Check/INFO]: [forge] Found status: BETA Current: 39.0.76 Target: 39.0.76
[05:12:39] [main/WARN]: Assets URL 'union:/home/sid_637640/minecraft_forge_118/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2367!/assets/.mcassetsroot' uses unexpected schema
[05:12:39] [main/WARN]: Assets URL 'union:/home/sid_637640/minecraft_forge_118/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2367!/data/.mcassetsroot' uses unexpected schema
[05:12:40] [main/INFO]: Registering commands with com.sk89q.worldedit.forge.ForgePlatform
[05:12:40] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[05:12:40] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[05:12:40] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[05:12:40] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[05:12:40] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[05:12:40] [main/WARN]: Ambiguity between arguments [waypoint, create, name, dimension, location, color, announce] and [waypoint, create, name, dimension, location, color, player] with inputs: [true, false]
[05:12:40] [main/WARN]: Ambiguity between arguments [waypoint, delete, name, announce] and [waypoint, delete, name, player] with inputs: [true, false]
[05:12:40] [main/INFO]: Hello, World! (You will see this line every time server resources reload)
[05:12:40] [main/INFO]: Loaded script server_scripts:script.js in 0.004 s
[05:12:40] [main/INFO]: Loaded 1/1 KubeJS server scripts in 0.009 s
[05:12:40] [main/INFO]: Scripts loaded
[05:12:40] [main/INFO]: Registered custom recipe handler for type kubejs:shaped
[05:12:40] [main/INFO]: Registered custom recipe handler for type kubejs:shapeless
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:crafting_shaped
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:crafting_shapeless
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:stonecutting
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:smelting
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:blasting
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:smoking
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:campfire_cooking
[05:12:40] [main/INFO]: Registered custom recipe handler for type minecraft:smithing
[05:12:40] [main/INFO]: Scanning recipes...
[05:12:40] [main/INFO]: Reloading ResourceManager: KubeJS Virtual Data Pack [low priority], Default, forge-1.18.1-39.0.76-universal.jar, carryon-1.18.1-1.17.0.7.jar, FallingTree-1.18.1-3.2.0b2.jar, MouseTweaks-forge-mc1.18-2.21.jar, CosmeticArmorReworked-1.18.1-v1a.jar, waystones-forge-1.18.1-9.0.3.jar, journeymap-1.18.1-5.8.0beta11.jar, balm-2.4.1+0.jar, ironchest-1.18-13.0.7.jar, inventorysorter-1.18-19.0.0.jar, curios-forge-1.18.1-5.0.6.0.jar, angelring-1.18-1.5.0.jar, configured-1.5.1-1.18.1.jar, cleancut-mc1.18-3.0-forge.jar, clienttweaks-forge-1.18-7.0.0.jar, jei-1.18.1-9.2.1.69.jar, quickhomes-1.18.1-1.3.0-forge.jar, Controlling-forge-1.18.1-9.0+14.jar, sit-1.18-1.3.1.jar, worldedit-mod-7.2.9.jar, elevatorid-1.18-1.8.3.jar, EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar, EditSign-1.18.1-2.2.7.jar, creeperconfetti-3.10.jar, TravelersBackpack-1.18.1-7.0.1.jar, signpost-1.18.1-2.00.4.jar, rhino-forge-1801.1.8-build.99.jar, architectury-3.6.17.jar, kubejs-forge-1801.4.2-build.298.jar, KubeJS Resource Pack [data], KubeJS Virtual Data Pack [high priority]
[05:12:40] [Worker-Main-74/INFO]: [enchantments] Found 0 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-76/INFO]: [block_entity_types] Found 0 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-73/INFO]: [structure_features] Found 0 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-72/INFO]: [potions] Found 0 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-79/INFO]: [mob_effects] Found 0 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-77/INFO]: [game_events] Found 2 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-81/INFO]: [fluids] Found 3 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-86/INFO]: [functions] Found 0 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-80/INFO]: [entity_types] Found 14 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-75/INFO]: [blocks] Found 238 tags, added 0 objects, removed 0 objects
[05:12:40] [Worker-Main-78/INFO]: [items] Found 272 tags, added 0 objects, removed 0 objects
[05:12:41] [Worker-Main-88/INFO]: Found 1193 recipes and 0 failed recipes in 52.43 ms
[05:12:41] [Worker-Main-88/INFO]: Posted recipe events in 992.2 ?s
[05:12:41] [Worker-Main-88/INFO]: Modified & removed recipes in 15.84 ms
[05:12:41] [Worker-Main-88/INFO]: Added recipes in 287.8 ?s
[05:12:41] [Worker-Main-88/INFO]: Added 0 recipes, removed 0 recipes, modified 0 recipes, with 0 failed recipes and 0 fall-backed recipes
[05:12:41] [Worker-Main-88/INFO]: Loaded 1186 advancements
[05:12:42] [Server thread/INFO]: Starting minecraft server version 1.18.1
[05:12:42] [Server thread/INFO]: Loading properties
[05:12:42] [Server thread/INFO]: Default game type: SURVIVAL
[05:12:42] [Server thread/INFO]: Generating keypair
[05:12:43] [Server thread/INFO]: Starting Minecraft server on 172.106.131.134:25825
[05:12:43] [Server thread/INFO]: Using epoll channel type
[05:12:43] [Server thread/INFO]: Loading JourneyMap Forge Configs
[05:12:43] [Thread-0/INFO]: Loading JourneyMap Forge Configs
[05:12:43] [Thread-0/INFO]: Loading JourneyMap Forge Configs
[05:12:43] [Server thread/INFO]: Preparing level "Land of Luga"
[05:12:43] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[05:12:44] [Worker-Main-78/INFO]: Preparing spawn area: 0%
[05:12:44] [Worker-Main-75/INFO]: Preparing spawn area: 0%
[05:12:44] [Worker-Main-83/INFO]: Preparing spawn area: 0%
[05:12:44] [Worker-Main-75/INFO]: Preparing spawn area: 0%
[05:12:45] [Worker-Main-87/INFO]: Preparing spawn area: 0%
[05:12:45] [Worker-Main-88/INFO]: Preparing spawn area: 0%
[05:12:46] [Worker-Main-84/INFO]: Preparing spawn area: 13%
[05:12:46] [Worker-Main-77/INFO]: Preparing spawn area: 32%
[05:12:47] [Worker-Main-75/INFO]: Preparing spawn area: 79%
[05:12:47] [Server thread/INFO]: Time elapsed: 4338 ms
[05:12:47] [Server thread/INFO]: Done (4.493s)! For help, type "help"
[05:12:47] [Server thread/INFO]: Starting GS4 status listener
[05:12:47] [Server thread/INFO]: Thread Query Listener started
[05:12:47] [Query Listener #1/INFO]: Query running on 172.106.131.134:25825
[05:12:47] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[05:13:16] [Server thread/INFO]: Stopping the server
[05:13:16] [Server thread/INFO]: Stopping server
[05:13:16] [Server thread/INFO]: Saving players
[05:13:16] [Server thread/INFO]: Saving worlds
[05:13:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Land of Luga]'/minecraft:overworld
[05:13:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Land of Luga]'/minecraft:the_nether
[05:13:16] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Land of Luga]'/minecraft:the_end
[05:13:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (Land of Luga): All chunks are saved
[05:13:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[05:13:16] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[05:13:16] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[05:13:16] [Server thread/INFO]: Thread Query Listener stopped

**Comment by lulabyte** [comment]
On further investigation, I'm not entirely sure it's causing a RAM spike as my server info panel may just be delayed. I'll check actual performance. But I am worried about the "Potentially Dangerous" errors.

**Comment by LatvianModder** [comment]
Those prefix errors are fine, you can ignore those. They happen when a mod adds something in another mod, in this case, forge adds milk fluid in minecraft

**Comment by lulabyte** [comment]
Awesome, thank you so much for your speedy response.

**Comment by Spiker985** [comment]
@lulabyte Is this still a concern, and do you have supporting data?
