### ISSUE TITLE
Conflict with ReinforcedChests/Barrels/ShulkerBoxes mod

### ISSUE THREAD

**Issue by PIPILAN** [KubeJS-Mods/KubeJS#506]
### Minecraft Version

1.19.2

### KubeJS Version

1902.6.0-build.86

### Rhino Version

1902.2.1-build.242

### Architectury Version

6.2.46

### Forge/Fabric Version

Fabric 0.14.9

### Describe your issue

The game crashed when I switched to the crafting inventory on the second page (where the ReinforcedChests/Barrels/ShulkerBoxes mod is)

### Crash report/logs

https://pastebin.com/Yp9kaq6z

**Comment by ChiefArug** [comment]
I do not think this is a conflict between KubeJS and the Reinforced storage mods, the stack trace only mentions `reinfshulker`.

It is crashing because the sprite/texture atlas is null, and KubeJS does not do anything with that afaik (although a script potentially could). Does this still happen if you remove just KubeJS?

**Comment by PIPILAN** [comment]
> 我不认为这是KubeJS和强化存储模组之间的冲突，堆栈跟踪只提到了 。`reinfshulker`
> 
> 它正在崩溃，因为精灵/纹理图集为空，并且KubeJS不会对该afaik执行任何操作（尽管脚本可能）。如果您只删除 KubeJS，这种情况还会发生吗？



> I do not think this is a conflict between KubeJS and the Reinforced storage mods, the stack trace only mentions .`reinfshulker`
> 
> It is crashing because the sprite/texture atlas is null, and KubeJS does not do anything with that afaik (although a script potentially could). Does this still happen if you remove just KubeJS?

Just delete kubejs and the crash won't happen, you can try it

**Comment by PIPILAN** [comment]
I ran a separate test
Mods:
![image](https://user-images.githubusercontent.com/38380796/196076943-7132aed2-4b71-4133-80e8-fdb5dfea6d52.png)
Crash report:
https://pastebin.com/x7tLm5cr
Log:
https://pastebin.com/pFjzaCYG

I found this log that might be helpful to you
`[10:37:58] [Render thread/ERROR]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5667()" because "p0" is null
	at dev.latvian.mods.kubejs.net.SyncStagesMessage.handle(SyncStagesMessage.java:53) ~[kubejs-fabric-1902.6.0-build.95.jar:?]
	at dev.architectury.networking.simple.MessageDecoder.lambda$createReceiver$0(MessageDecoder.java:52) ~[architectury-6.2.46-fabric.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]`

**Comment by ChiefArug** [comment]
That error has nothing to do with the crash you are getting

**Comment by PIPILAN** [comment]
Then I don't know. We've got all the modules up there. When I delete kubejs or ReinforcedChests/Barrels/ShulkerBoxes

The game will run properly when you switch the creative tab.

> That error has nothing to do with the crash you are getting

Then I don't know. We've got all the modules up there. When I delete kubejs or ReinforcedChests/Barrels/ShulkerBoxes

The game will run properly when you switch the creative tab.

**Comment by PIPILAN** [comment]
A new clue.

https://github.com/Aton-Kish/reinforced-chests/issues/36

log (without kubejs)

```
[23:18:57] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 reinfshulker:textures/atlas/copper_shulker_boxes.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 reinfshulker:textures/atlas/iron_shulker_boxes.png-atlas
[23:18:57] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[23:18:57] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:18:57] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:18:57] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 reinfshulker:textures/atlas/netherite_shulker_boxes.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 reinfshulker:textures/atlas/diamond_shulker_boxes.png-atlas
[23:18:57] [Render thread/INFO]: Created: 512x256x4 reinfshulker:textures/atlas/gold_shulker_boxes.png-atlas
[23:18:58] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[23:18:58] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[23:18:58] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:18:58] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
```

log (with kubejs)

```
[23:19:58] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[23:19:58] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[23:19:58] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[23:19:58] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[23:19:58] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[23:19:58] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[23:19:58] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[23:19:59] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[23:19:59] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[23:19:59] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[23:19:59] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
```

It seems that the kubejs prevents my mod from creating atlas textures.
