### ISSUE TITLE
KubeJS seems to fail when compatible with FTB Chunks?

### ISSUE THREAD

**Issue by EvanHsieh0415** [KubeJS-Mods/KubeJS#725]
### Minecraft Version

1.20.1

### KubeJS Version

2001.6.3-build.52

### Rhino Version

2001.6.3-build.52

### Architectury Version

9.1.12

### Forge/Fabric Version

Fabric 0.14.22

### Describe your issue

```java
[18:17:09] [Render thread/ERROR] (KubeJS) Failed to load plugin dev.ftb.mods.ftbchunks.integration.kubejs.FTBChunksKubeJSPlugin from source ftbchunks: java.lang.ClassNotFoundException: dev.ftb.mods.ftbchunks.integration.kubejs.FTBChunksKubeJSPlugin
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: java.lang.ClassNotFoundException: dev.ftb.mods.ftbchunks.integration.kubejs.FTBChunksKubeJSPlugin
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at dev.latvian.mods.kubejs.util.KubeJSPlugins.lambda$loadFromFile$2(KubeJSPlugins.java:69)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at dev.latvian.mods.kubejs.util.KubeJSPlugins.loadFromFile(KubeJSPlugins.java:77)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at dev.latvian.mods.kubejs.util.KubeJSPlugins.load(KubeJSPlugins.java:38)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at dev.latvian.mods.kubejs.util.KubeJSPlugins.load(KubeJSPlugins.java:27)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at dev.latvian.mods.kubejs.KubeJS.<init>(KubeJS.java:126)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at dev.latvian.mods.kubejs.fabric.KubeJSFabric.onInitialize(KubeJSFabric.java:34)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_310.redirect$dog000$notenoughcrashes$catchFabricInit(class_310.java:25511)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:458)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:211)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
[18:17:09] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

### Crash report/logs

https://mclo.gs/v9syz9i

**Comment by MaxNeedsSnacks** [comment]
Not a KubeJS issue, FTB Chunks does not have a KubeJS plugin anymore but still declares it in its plugins file. This error should be harmless anyways.
