### ISSUE TITLE
KubeJS breaks recipes from Tinkerer's Smithing

### ISSUE THREAD

**Issue by mintynoura** [KubeJS-Mods/KubeJS#822]
### Minecraft Version

Quilt 1.20.1

### KubeJS Version

kubejs-fabric-2001.6.4-build.138

### Rhino Version

rhino-fabric-2001.2.2-build.18

### Architectury Version

architectury-9.1.12-fabric

### Forge/Fabric Version

Quilt 0.25.0

### Describe your issue

It seems that using startup scripts from KubeJS to modify or register anything (not necessarily related to anvils/smithing) will disable all the crafting and smithing recipes from Tinkerer's Smithing, as well as the vanilla anvil repairing mechanics. The developers of Tinkerer's Smithing responded [here](https://github.com/sisby-folk/tinkerers-smithing/issues/40) explaining that the issue can't be fixed on their side, so I'm reporting it here. The Minecraft/KubeJS logs don't seem to mention anything related to the problem.

![323741601-f4aeed8d-2911-4a9d-a501-bf90cb937c71](https://github.com/KubeJS-Mods/KubeJS/assets/107040228/b2dabd1c-744a-4922-ad36-895b6eceb357)

![323742263-8dd5da10-53e8-4949-a344-1b6577d87445](https://github.com/KubeJS-Mods/KubeJS/assets/107040228/09ecfc01-6550-4e5a-b80d-6ff3938bc00a)

### Crash report/logs

_N/A_

**Comment by ChiefArug** [comment]
It's unlikely that KubeJS will change those mixins, but if the mod author wants to/someone wants to PR it then they can make a KubeJS plugin to register their java generated recipes.
https://github.com/KubeJS-Mods/KubeJS/blob/220391f6d46609b30a754ce60c2cce943d699f89/common/src/main/java/dev/latvian/mods/kubejs/KubeJSPlugin.java#L110-L114

The steps for doing this are:
- Make a class that extends KubeJSPlugin
- Override `injectRuntimeRecipes` and add your recipes there
- Cancel your normal recipe adding if KubeJS is installed (though that seems like it is already happening here)
- Add a kubejs.plugins.txt to the root of your jar (the `resources` folder) that contains a single line of the full classpath of your KubeJS plugin, ie `mods.chiefarug.moddymcmodface.compat.kubejs.ModdyKubeJSPlugin`

**Comment by abrossimow** [comment]
I get this thrown at me:
`[KubeJS Recipe Event Worker 0/ERROR]: [Tinkerer's Smithing] Cowardly refusing to access an unloaded tag ingredient: {"tag":"create:stone_types/scorchia"}
java.lang.IllegalStateException: A tag ingredient was accessed before tags are loaded - This can break recipes! Report this to the mod in the trace below.
	at net.minecraft.class_1856.isFootgun(class_1856.java:2522) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.handler$klk000$tinkerers_smithing$getMatchingStacks(class_1856.java:2530) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8105(class_1856.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1856.method_8093(class_1856.java:63) ~[client-intermediary.jar:?]
	at dev.latvian.mods.kubejs.recipe.SingleItemMatch.contains(SingleItemMatch.java:15) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.component.ItemComponents$1.isInput(ItemComponents.java:50) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.component.ItemComponents$1.isInput(ItemComponents.java:17) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.component.RecipeComponentValue.isInput(RecipeComponentValue.java:36) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.RecipeJS.hasInput(RecipeJS.java:331) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.filter.InputFilter.test(InputFilter.java:15) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:498) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at dev.latvian.mods.kubejs.recipe.RecipesEventJS$RecipeStreamFilter.test(RecipesEventJS.java:495) ~[kubejs-fabric-2001.6.5-build.14.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:?]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]`

After using murphy-slaw's fix.
It is thrown by this:
https://github.com/sisby-folk/tinkerers-smithing/blob/1.20/src/main/java/folk/sisby/tinkerers_smithing/mixin/IngredientMixin.java

Might this be fixed with the same approach?

**Comment by MaxNeedsSnacks** [comment]
As pointed out, murphy-slaw has since created a fix mod for this. It's unfortunately unlikely that we'll be doing sweeping refactors to RecipeManager stuff on versions below 1.21, so I'll be closing this for now. Sorry for the troubles!
